### PR TITLE
Add a new test case to verify data consistency

### PR DESCRIPTION
**Pull request by jerrinsg**
Added a new test to verify if clients see a consistent view of keys in the Redis database.

To run the test: 
```
$ cd tests
$  ~/go-pmem/bin/go test -run=Pipeline
```

### CODE REVIEW

**Comment by jerrinsg** [comment]
The tests need to be run two times to see the issue. On the first run, client 1 increments the value of `a` and `b` 2000 times. Simultaneously, client 2 reads the value of `a` and `b`, and sets the value of `c` as `a+b`. It induces a crash soon after.

On the next run, the value of `a`, `b`, and `c` is read back and verified to ensure that `c` is less than or equal to `a+b`. The test may need to be run a few times to see the issue. On each separate invocation of the test, the Redis data file has to deleted - 
`$ rm ./database`

**Comment by jerrinsg** [comment]
Output from a run where the tests failed:
```
➜  tests git:(tests) ✗ ~/go-pmem/bin/go test -run=Pipeline
First time initialization
Go-redis is ready to accept connections
Client 2 - Got a as  58  and b as  58 . Set c as  116
Reading from client: EOF
Reading from client: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ae8b4]

goroutine 60 [running]:
github.com/vmware-samples/go-redis-pmem/tests.client2()
	/home/jerrin/gocode/src/github.com/vmware-samples/go-redis-pmem/tests/pipeline_test.go:70 +0x2b4
created by github.com/vmware-samples/go-redis-pmem/tests.client1
	/home/jerrin/gocode/src/github.com/vmware-samples/go-redis-pmem/tests/pipeline_test.go:44 +0x30b
exit status 2
FAIL	github.com/vmware-samples/go-redis-pmem/tests	6.080s


➜  tests git:(tests) ✗ ~/go-pmem/bin/go test -run=Pipeline
Not a first time intialization
Go-redis is ready to accept connections
Got values as: a =  54  b =  54  c =  116
--- FAIL: TestPipeline (2.00s)
    pipeline_test.go:123: Invalid values
FAIL
exit status 1
FAIL	github.com/vmware-samples/go-redis-pmem/tests	2.008s
```

**Comment by jerrinsg** [comment]
Rebasing branch after dropping commit 56492d09d3e13d83b4d0a5cce83d7694c175398b

**Comment by pratapsu** [comment]
Jerrin: this code looks good. A few questions: 

1) the test fails easily. Correct? Ie, it is not a hard to reproduce race condition. 

2) Now that you have reverted the optmization, does the test pass on top of trunck? 

3) I recall asking you to set up a nightly test framework. Have you done so, I don't recall seeing any review requests for that? Ensure this test is a part of that nightly suite.

**Comment by jerrinsg** [comment]
Hi Pratap,

1. The tests actually do not fail easily. Multiple attempts are required to see the tests failing. I usually see the tests failing once in 3 or 4 attempts.

2. Yes, the tests always pass with the optimization reverted (56492d0).

3. I haven't yet sent out a review request for the nightly test framework. I will add this test as part of the framework.

**Comment by jerrinsg** [comment]
Rebasing on top of master.

**Pull request merged**
